-- Generado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   en:        2025-09-15 16:47:36 CLST
--   sitio:      Oracle Database 21c
--   tipo:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE AFP 
    ( 
     ID_AFP NUMBER (4)  NOT NULL , 
     NOMBRE VARCHAR2 (60)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE AFP 
    ADD CONSTRAINT PK_AFP PRIMARY KEY ( ID_AFP ) ;

ALTER TABLE AFP 
    ADD CONSTRAINT UQ_AFP_NOMBRE UNIQUE ( NOMBRE ) ;

CREATE TABLE ATENCION 
    ( 
     ID_ATENCION    NUMBER (12)  NOT NULL , 
     FECHA_ATENCION DATE  NOT NULL , 
     TIPO_ATENCION  VARCHAR2 (12)  NOT NULL , 
     RUT_PACIENTE   VARCHAR2 (15)  NOT NULL , 
     RUT_MEDICO     VARCHAR2 (15)  NOT NULL , 
     DIAGNOSTICO    VARCHAR2 (300) , 
     MONTO_PAGADO   NUMBER (10,2) DEFAULT 0  NOT NULL 
    ) 
    LOGGING 
;
CREATE INDEX IX_ATE_PAC ON ATENCION 
    ( 
     RUT_PACIENTE ASC 
    ) 
;
CREATE INDEX IX_ATE_MED ON ATENCION 
    ( 
     RUT_MEDICO ASC 
    ) 
;

ALTER TABLE ATENCION 
    ADD CONSTRAINT CHK_ATE_TIPO 
    CHECK (UPPER(TIPO_ATENCION) IN ('GENERAL','URGENCIA','PREVENTIVA'))
;
ALTER TABLE ATENCION 
    ADD CONSTRAINT PK_ATENCION PRIMARY KEY ( ID_ATENCION ) ;

CREATE TABLE ATENCION_EXAMEN 
    ( 
     ID_ATENCION     NUMBER (12)  NOT NULL , 
     COD_EXAMEN      VARCHAR2 (12)  NOT NULL , 
     RUT_PACIENTE    VARCHAR2 (15)  NOT NULL , 
     RUT_MEDICO      VARCHAR2 (15)  NOT NULL , 
     FECHA_SOLICITUD DATE  NOT NULL , 
     RESULTADO       VARCHAR2 (1000) , 
     FECHA_RESULTADO DATE 
    ) 
    LOGGING 
;
CREATE INDEX IX_AE_EXAMEN ON ATENCION_EXAMEN 
    ( 
     COD_EXAMEN ASC 
    ) 
;

ALTER TABLE ATENCION_EXAMEN 
    ADD CONSTRAINT CHK_AE_FECHAS 
    CHECK (FECHA_RESULTADO IS NULL OR FECHA_RESULTADO >= FECHA_SOLICITUD)
;
ALTER TABLE ATENCION_EXAMEN 
    ADD CONSTRAINT PK_ATENCION_EXAMEN PRIMARY KEY ( ID_ATENCION, COD_EXAMEN ) ;

CREATE TABLE COMUNA 
    ( 
     ID_COMUNA NUMBER (6)  NOT NULL , 
     NOMBRE    VARCHAR2 (80)  NOT NULL , 
     ID_REGION NUMBER (4)  NOT NULL 
    ) 
    LOGGING 
;
CREATE INDEX IX_COMUNA_REGION ON COMUNA 
    ( 
     ID_REGION ASC 
    ) 
;

ALTER TABLE COMUNA 
    ADD CONSTRAINT PK_COMUNA PRIMARY KEY ( ID_COMUNA ) ;

ALTER TABLE COMUNA 
    ADD CONSTRAINT UQ_COMUNA_NOMBRE UNIQUE ( NOMBRE ) ;

CREATE TABLE ESPECIALIDAD 
    ( 
     ID_ESPECIALIDAD NUMBER (6)  NOT NULL , 
     NOMBRE          VARCHAR2 (100)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE ESPECIALIDAD 
    ADD CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY ( ID_ESPECIALIDAD ) ;

ALTER TABLE ESPECIALIDAD 
    ADD CONSTRAINT UQ_ESPECIALIDAD_NOMBRE UNIQUE ( NOMBRE ) ;

CREATE TABLE EXAMEN 
    ( 
     COD_EXAMEN         VARCHAR2 (12)  NOT NULL , 
     NOMBRE             VARCHAR2 (120)  NOT NULL , 
     TIPO_MUESTRA       VARCHAR2 (60)  NOT NULL , 
     CONDICIONES_PREVIA VARCHAR2 (200) 
    ) 
    LOGGING 
;

ALTER TABLE EXAMEN 
    ADD CONSTRAINT PK_EXAMEN PRIMARY KEY ( COD_EXAMEN ) ;

ALTER TABLE EXAMEN 
    ADD CONSTRAINT UQ_EXAMEN_NOMBRE UNIQUE ( NOMBRE ) ;

CREATE TABLE INSTITUCION_SALUD 
    ( 
     ID_INSTITUCION NUMBER (4)  NOT NULL , 
     NOMBRE         VARCHAR2 (60)  NOT NULL , 
     TIPO           VARCHAR2 (10)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE INSTITUCION_SALUD 
    ADD CONSTRAINT CHK_INS_TIPO 
    CHECK (UPPER(TIPO) IN ('FONASA','ISAPRE','OTRO'))
;
ALTER TABLE INSTITUCION_SALUD 
    ADD CONSTRAINT PK_INSTITUCION PRIMARY KEY ( ID_INSTITUCION ) ;

ALTER TABLE INSTITUCION_SALUD 
    ADD CONSTRAINT UQ_INSTITUCION_NOMBRE UNIQUE ( NOMBRE ) ;

CREATE TABLE MEDICO 
    ( 
     RUT_MEDICO      VARCHAR2 (15)  NOT NULL , 
     NOMBRE          VARCHAR2 (120)  NOT NULL , 
     FECHA_INGRESO   DATE  NOT NULL , 
     ID_ESPECIALIDAD NUMBER (6)  NOT NULL , 
     ID_UNIDAD       NUMBER (4)  NOT NULL , 
     ID_AFP          NUMBER (4)  NOT NULL , 
     ID_INSTITUCION  NUMBER (4)  NOT NULL , 
     RUT_SUPERVISOR  VARCHAR2 (15) 
    ) 
    LOGGING 
;
CREATE INDEX IX_MED_SUP ON MEDICO 
    ( 
     RUT_SUPERVISOR ASC 
    ) 
;

ALTER TABLE MEDICO 
    ADD CONSTRAINT PK_MEDICO PRIMARY KEY ( RUT_MEDICO ) ;

CREATE TABLE PACIENTE 
    ( 
     RUT_PACIENTE     VARCHAR2 (15)  NOT NULL , 
     NOMBRE           VARCHAR2 (120)  NOT NULL , 
     SEXO             CHAR (1)  NOT NULL , 
     FECHA_NACIMIENTO DATE  NOT NULL , 
     DIRECCION        VARCHAR2 (160)  NOT NULL , 
     ID_COMUNA        NUMBER (6)  NOT NULL , 
     TIPO_PACIENTE    VARCHAR2 (15)  NOT NULL 
    ) 
    LOGGING 
;
CREATE INDEX IX_PAC_COMUNA ON PACIENTE 
    ( 
     ID_COMUNA ASC 
    ) 
;

ALTER TABLE PACIENTE 
    ADD CONSTRAINT CHK_PAC_SEXO 
    CHECK (UPPER(SEXO) IN ('M','F','O'))
;


ALTER TABLE PACIENTE 
    ADD CONSTRAINT CHK_PAC_TIPO 
    CHECK (UPPER(TIPO_PACIENTE) IN ('ESTUDIANTE','FUNCIONARIO','EXTERNO'))
;
ALTER TABLE PACIENTE 
    ADD CONSTRAINT PK_PACIENTE PRIMARY KEY ( RUT_PACIENTE ) ;

CREATE TABLE PAGO 
    ( 
     ID_PAGO     NUMBER (12)  NOT NULL , 
     ID_ATENCION NUMBER (12)  NOT NULL , 
     TIPO_PAGO   VARCHAR2 (12)  NOT NULL , 
     MONTO       NUMBER (10,2)  NOT NULL , 
     FECHA_PAGO  DATE  NOT NULL 
    ) 
    LOGGING 
;
CREATE INDEX IX_PAGO_ATENCION ON PAGO 
    ( 
     ID_ATENCION ASC 
    ) 
;

ALTER TABLE PAGO 
    ADD CONSTRAINT CHK_PAGO_TIPO 
    CHECK (UPPER(TIPO_PAGO) IN ('EFECTIVO','TARJETA','CONVENIO'))
;
ALTER TABLE PAGO 
    ADD CONSTRAINT PK_PAGO PRIMARY KEY ( ID_PAGO ) ;

ALTER TABLE PAGO 
    ADD CONSTRAINT UQ_PAGO_ATENCION UNIQUE ( ID_ATENCION ) 
    USING INDEX IX_PAGO_ATENCION ;

CREATE TABLE REGION 
    ( 
     ID_REGION NUMBER (4)  NOT NULL , 
     NOMBRE    VARCHAR2 (80)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE REGION 
    ADD CONSTRAINT PK_REGION PRIMARY KEY ( ID_REGION ) ;

ALTER TABLE REGION 
    ADD CONSTRAINT UQ_REGION_NOMBRE UNIQUE ( NOMBRE ) ;

CREATE TABLE UNIDAD 
    ( 
     ID_UNIDAD NUMBER (4)  NOT NULL , 
     NOMBRE    VARCHAR2 (80)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE UNIDAD 
    ADD CONSTRAINT PK_UNIDAD PRIMARY KEY ( ID_UNIDAD ) ;

ALTER TABLE UNIDAD 
    ADD CONSTRAINT UQ_UNIDAD_NOMBRE UNIQUE ( NOMBRE ) ;

ALTER TABLE ATENCION_EXAMEN 
    ADD CONSTRAINT FK_AE_ATE FOREIGN KEY 
    ( 
     ID_ATENCION
    ) 
    REFERENCES ATENCION 
    ( 
     ID_ATENCION
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ATENCION_EXAMEN 
    ADD CONSTRAINT FK_AE_EXA FOREIGN KEY 
    ( 
     COD_EXAMEN
    ) 
    REFERENCES EXAMEN 
    ( 
     COD_EXAMEN
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ATENCION_EXAMEN 
    ADD CONSTRAINT FK_AE_MED FOREIGN KEY 
    ( 
     RUT_MEDICO
    ) 
    REFERENCES MEDICO 
    ( 
     RUT_MEDICO
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ATENCION_EXAMEN 
    ADD CONSTRAINT FK_AE_PAC FOREIGN KEY 
    ( 
     RUT_PACIENTE
    ) 
    REFERENCES PACIENTE 
    ( 
     RUT_PACIENTE
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ATENCION 
    ADD CONSTRAINT FK_ATE_MED FOREIGN KEY 
    ( 
     RUT_MEDICO
    ) 
    REFERENCES MEDICO 
    ( 
     RUT_MEDICO
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ATENCION 
    ADD CONSTRAINT FK_ATE_PAC FOREIGN KEY 
    ( 
     RUT_PACIENTE
    ) 
    REFERENCES PACIENTE 
    ( 
     RUT_PACIENTE
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE COMUNA 
    ADD CONSTRAINT FK_COMUNA_REGION FOREIGN KEY 
    ( 
     ID_REGION
    ) 
    REFERENCES REGION 
    ( 
     ID_REGION
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE MEDICO 
    ADD CONSTRAINT FK_MED_AFP FOREIGN KEY 
    ( 
     ID_AFP
    ) 
    REFERENCES AFP 
    ( 
     ID_AFP
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE MEDICO 
    ADD CONSTRAINT FK_MED_ESP FOREIGN KEY 
    ( 
     ID_ESPECIALIDAD
    ) 
    REFERENCES ESPECIALIDAD 
    ( 
     ID_ESPECIALIDAD
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE MEDICO 
    ADD CONSTRAINT FK_MED_INS FOREIGN KEY 
    ( 
     ID_INSTITUCION
    ) 
    REFERENCES INSTITUCION_SALUD 
    ( 
     ID_INSTITUCION
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE MEDICO 
    ADD CONSTRAINT FK_MED_SUP FOREIGN KEY 
    ( 
     RUT_SUPERVISOR
    ) 
    REFERENCES MEDICO 
    ( 
     RUT_MEDICO
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE MEDICO 
    ADD CONSTRAINT FK_MED_UNI FOREIGN KEY 
    ( 
     ID_UNIDAD
    ) 
    REFERENCES UNIDAD 
    ( 
     ID_UNIDAD
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE PACIENTE 
    ADD CONSTRAINT FK_PAC_COMUNA FOREIGN KEY 
    ( 
     ID_COMUNA
    ) 
    REFERENCES COMUNA 
    ( 
     ID_COMUNA
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE PAGO 
    ADD CONSTRAINT FK_PAGO_ATENCION FOREIGN KEY 
    ( 
     ID_ATENCION
    ) 
    REFERENCES ATENCION 
    ( 
     ID_ATENCION
    ) 
    NOT DEFERRABLE 
;



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             7
-- ALTER TABLE                             40
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
