
CREATE TABLE PACIENTE (
  ID_PACIENTE       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RUT               VARCHAR2(12) NOT NULL,
  DV                CHAR(1)      NOT NULL,
  NOMBRE            VARCHAR2(100) NOT NULL,
  DIRECCION         VARCHAR2(200) NOT NULL,
  CIUDAD            VARCHAR2(80)  NOT NULL,
  ID_COMUNA         NUMBER NOT NULL,
  ID_REGION         NUMBER NOT NULL,
  EDAD              NUMBER(3),
  CONSTRAINT CHK_PACIENTE_DV CHECK (REGEXP_LIKE(DV, '^[0-9Kk]$'))
);

CREATE TABLE MEDICO (
  ID_MEDICO         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RUT               VARCHAR2(12) NOT NULL,
  DV                CHAR(1)      NOT NULL,
  NOMBRE            VARCHAR2(100) NOT NULL,
  TELEFONO          VARCHAR2(20) NOT NULL UNIQUE,
  ID_ESPECIALIDAD   NUMBER GENERATED ALWAYS AS IDENTITY,
  CONSTRAINT CHK_MEDICO_DV CHECK (REGEXP_LIKE(DV, '^[0-9Kk]$'))
);

CREATE TABLE DIGITADOR (
  ID_DIGITADOR      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RUT               VARCHAR2(12) NOT NULL,
  DV                CHAR(1)      NOT NULL,
  NOMBRE            VARCHAR2(100) NOT NULL,
  CONSTRAINT CHK_DIGITADOR_DV CHECK (REGEXP_LIKE(DV, '^[0-9Kk]$'))
);

CREATE TABLE RECETA (
  ID_RECETA         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FECHA_EMISION     DATE NOT NULL,
  FECHA_EXPIRACION  DATE,
  OBSERVACIONES     VARCHAR2(300),
  TIPO_RECETA       VARCHAR2(15) NOT NULL,
  ID_PACIENTE       NUMBER NOT NULL,
  ID_MEDICO         NUMBER NOT NULL,
  ID_DIGITADOR      NUMBER NOT NULL,
  CONSTRAINT CHK_TIPO_RECETA CHECK (UPPER(TIPO_RECETA) IN
    ('DIGITAL','MAGISTRAL','RETENIDA','GENERAL','VETERINARIA')),
  CONSTRAINT FK_RECETA_PAC FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
  CONSTRAINT FK_RECETA_MED FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
  CONSTRAINT FK_RECETA_DIG FOREIGN KEY (ID_DIGITADOR) REFERENCES DIGITADOR(ID_DIGITADOR)
);

CREATE TABLE MEDICAMENTO (
  ID_MEDICAMENTO    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE            VARCHAR2(100) NOT NULL,
  DOSIS             VARCHAR2(50)  NOT NULL,
  STOCK             NUMBER(6)     NOT NULL,
  TIPO              VARCHAR2(10)  NOT NULL,
  CONSTRAINT CHK_MEDICAMENTO_TIPO CHECK (UPPER(TIPO) IN ('GENÉRICO','GENERIC','MARCA'))
);

CREATE TABLE RECETA_MEDICAMENTO (
  ID_RECETA         NUMBER NOT NULL,
  ID_MEDICAMENTO    NUMBER NOT NULL,
  CONSTRAINT PK_RECETA_MEDICAMENTO PRIMARY KEY (ID_RECETA, ID_MEDICAMENTO),
  CONSTRAINT FK_RM_RECETA FOREIGN KEY (ID_RECETA) REFERENCES RECETA(ID_RECETA),
  CONSTRAINT FK_RM_MED FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
);

CREATE TABLE PAGO (
  ID_PAGO           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_RECETA         NUMBER NOT NULL,
  MONTO             NUMBER(10,2) NOT NULL,
  FECHA_PAGO        DATE NOT NULL,
  TIPO              VARCHAR2(15),
  CONSTRAINT FK_PAGO_RECETA FOREIGN KEY (ID_RECETA) REFERENCES RECETA(ID_RECETA)
);

ALTER TABLE MEDICAMENTO
  ADD (PRECIO_UNITARIO NUMBER(10,2)
       CONSTRAINT CHK_PRECIO_UNIT CHECK (PRECIO_UNITARIO BETWEEN 1000 AND 2000000));

ALTER TABLE PAGO
  ADD CONSTRAINT CHK_TIPO_PAGO CHECK (UPPER(TIPO) IN ('EFECTIVO','TARJETA','TRANSFERENCIA'));

ALTER TABLE PACIENTE DROP COLUMN EDAD;
ALTER TABLE PACIENTE ADD (FECHA_NACIMIENTO DATE NOT NULL);
