
CREATE TABLE REGION (
  ID_REGION NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 7 INCREMENT BY 2) PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE COMUNA (
  ID_COMUNA NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  ID_REGION NUMBER NOT NULL,
  CONSTRAINT FK_COMUNA_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
);

CREATE SEQUENCE SEQ_COMUNA START WITH 1101 INCREMENT BY 6;

CREATE TABLE ESTADO_CIVIL (
  ID_ESTADO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(50) NOT NULL
);

CREATE TABLE GENERO (
  ID_GENERO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(20) NOT NULL
);

CREATE TABLE TITULACION (
  ID_TITULACION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE TITULO (
  ID_TITULO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  ID_TITULACION NUMBER NOT NULL,
  CONSTRAINT FK_TITULO_TITULACION FOREIGN KEY (ID_TITULACION) REFERENCES TITULACION(ID_TITULACION)
);

CREATE TABLE DOMINIO (
  ID_DOMINIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE IDIOMA (
  ID_IDIOMA NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 25 INCREMENT BY 3) PRIMARY KEY,
  NOMBRE VARCHAR2(50) NOT NULL
);

CREATE TABLE COMPANIA (
  ID_COMPANIA NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  DIRECCION VARCHAR2(150) NOT NULL,
  RENTA_PROMEDIO NUMBER(12,2) NOT NULL
);

CREATE SEQUENCE SEQ_COMPANIA START WITH 10 INCREMENT BY 5;

CREATE TABLE PERSONAL (
  ID_PERSONAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RUN VARCHAR2(12) NOT NULL,
  DV CHAR(1) NOT NULL,
  NOMBRE VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(120) UNIQUE,
  SUELDO NUMBER(12,2) NOT NULL,
  ID_COMPANIA NUMBER NOT NULL,
  ID_COMUNA NUMBER NOT NULL,
  ID_ESTADO NUMBER NOT NULL,
  ID_GENERO NUMBER NOT NULL,
  CONSTRAINT FK_PER_COMP FOREIGN KEY (ID_COMPANIA) REFERENCES COMPANIA(ID_COMPANIA),
  CONSTRAINT FK_PER_COMUNA FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA(ID_COMUNA),
  CONSTRAINT FK_PER_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_CIVIL(ID_ESTADO),
  CONSTRAINT FK_PER_GENERO FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO),
  CONSTRAINT CHK_DV CHECK (REGEXP_LIKE(DV, '^[0-9Kk]$')),
  CONSTRAINT CHK_SUELDO CHECK (SUELDO >= 450000)
);

INSERT INTO IDIOMA (NOMBRE) VALUES ('Inglés');
INSERT INTO IDIOMA (NOMBRE) VALUES ('Francés');
INSERT INTO IDIOMA (NOMBRE) VALUES ('Portugués');

INSERT INTO REGION (NOMBRE) VALUES ('Metropolitana');
INSERT INTO REGION (NOMBRE) VALUES ('Valparaíso');

INSERT INTO COMUNA (ID_COMUNA, NOMBRE, ID_REGION) VALUES (SEQ_COMUNA.NEXTVAL, 'Santiago', 7);
INSERT INTO COMUNA (ID_COMUNA, NOMBRE, ID_REGION) VALUES (SEQ_COMUNA.NEXTVAL, 'Maipú', 7);
INSERT INTO COMUNA (ID_COMUNA, NOMBRE, ID_REGION) VALUES (SEQ_COMUNA.NEXTVAL, 'Viña del Mar', 9);

INSERT INTO COMPANIA (ID_COMPANIA, NOMBRE, DIRECCION, RENTA_PROMEDIO) VALUES (SEQ_COMPANIA.NEXTVAL, 'Constructora Sur', 'Av. Central 123', 950000);
INSERT INTO COMPANIA (ID_COMPANIA, NOMBRE, DIRECCION, RENTA_PROMEDIO) VALUES (SEQ_COMPANIA.NEXTVAL, 'Servicios Norte', 'Calle 45 Norte', 720000);
INSERT INTO COMPANIA (ID_COMPANIA, NOMBRE, DIRECCION, RENTA_PROMEDIO) VALUES (SEQ_COMPANIA.NEXTVAL, 'Holding Central', 'Diagonal Oriente 789', 1100000);

SELECT C.NOMBRE AS EMPRESA, C.DIRECCION, C.RENTA_PROMEDIO,
       (C.RENTA_PROMEDIO * 1.10) AS RENTA_SIMULADA
FROM COMPANIA C
ORDER BY C.RENTA_PROMEDIO DESC, C.NOMBRE ASC;

SELECT C.ID_COMPANIA, C.NOMBRE, C.RENTA_PROMEDIO,
       (C.RENTA_PROMEDIO * 1.15) AS RENTA_SIMULADA
FROM COMPANIA C
ORDER BY C.RENTA_PROMEDIO ASC, C.NOMBRE DESC;
