
CREATE TABLE AFP (
  ID_AFP NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(80) UNIQUE NOT NULL
);

CREATE TABLE SALUD (
  ID_SALUD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(80) UNIQUE NOT NULL
);

CREATE TABLE EMPLEADO (
  ID_EMPLEADO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RUN VARCHAR2(12) NOT NULL,
  DV CHAR(1) NOT NULL,
  NOMBRES VARCHAR2(80) NOT NULL,
  APELLIDO_PATERNO VARCHAR2(60) NOT NULL,
  APELLIDO_MATERNO VARCHAR2(60),
  ACTIVO CHAR(1) DEFAULT 'S' NOT NULL,
  SUELDO NUMBER(12,2) NOT NULL,
  BONO_JEFATURA NUMBER(12,2),
  CORREO VARCHAR2(120),
  ID_AFP NUMBER NOT NULL,
  ID_SALUD NUMBER NOT NULL,
  CONSTRAINT UQ_EMPLEADO_RUN UNIQUE (RUN, DV),
  CONSTRAINT UQ_EMPLEADO_CORREO UNIQUE (CORREO),
  CONSTRAINT FK_EMPLEADO_AFP FOREIGN KEY (ID_AFP) REFERENCES AFP(ID_AFP),
  CONSTRAINT FK_EMPLEADO_SALUD FOREIGN KEY (ID_SALUD) REFERENCES SALUD(ID_SALUD),
  CONSTRAINT CHK_EMPLEADO_DV CHECK (REGEXP_LIKE(DV, '^[0-9Kk]$')),
  CONSTRAINT CHK_EMPLEADO_ACTIVO CHECK (UPPER(ACTIVO) IN ('S','N')),
  CONSTRAINT CHK_EMPLEADO_SUELDO CHECK (SUELDO >= 450000)
);

CREATE TABLE VENDEDOR (
  ID_VENDEDOR NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_EMPLEADO NUMBER NOT NULL,
  CONSTRAINT UQ_VENDEDOR_EMPLEADO UNIQUE (ID_EMPLEADO),
  CONSTRAINT FK_VENDEDOR_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE MEDIO_PAGO (
  ID_MEDIO_PAGO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(40) UNIQUE NOT NULL
);

CREATE TABLE PRODUCTO (
  ID_PRODUCTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  PRECIO NUMBER(10,2) NOT NULL,
  STOCK NUMBER(10,0) NOT NULL,
  CONSTRAINT CHK_PRODUCTO_PRECIO CHECK (PRECIO > 0),
  CONSTRAINT CHK_PRODUCTO_STOCK CHECK (STOCK >= 0)
);

CREATE TABLE VENTA (
  ID_VENTA NUMBER PRIMARY KEY,
  FECHA_VENTA DATE NOT NULL,
  MONTO_TOTAL NUMBER(12,2) NOT NULL,
  ID_VENDEDOR NUMBER NOT NULL,
  ID_MEDIO_PAGO NUMBER NOT NULL,
  CONSTRAINT FK_VENTA_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR),
  CONSTRAINT FK_VENTA_MEDIO FOREIGN KEY (ID_MEDIO_PAGO) REFERENCES MEDIO_PAGO(ID_MEDIO_PAGO)
);

CREATE SEQUENCE SEQ_VENTA START WITH 100 INCREMENT BY 1;

CREATE TABLE DETALLE_VENTA (
  ID_VENTA NUMBER NOT NULL,
  ID_PRODUCTO NUMBER NOT NULL,
  CANTIDAD NUMBER(10,0) NOT NULL,
  PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
  SUBTOTAL NUMBER(12,2) NOT NULL,
  CONSTRAINT PK_DETALLE_VENTA PRIMARY KEY (ID_VENTA, ID_PRODUCTO),
  CONSTRAINT FK_DV_VENTA FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID_VENTA),
  CONSTRAINT FK_DV_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
  CONSTRAINT CHK_DV_CANTIDAD CHECK (CANTIDAD > 0),
  CONSTRAINT CHK_DV_PRECIO CHECK (PRECIO_UNITARIO > 0),
  CONSTRAINT CHK_DV_SUBTOTAL CHECK (SUBTOTAL = CANTIDAD * PRECIO_UNITARIO)
);

ALTER TABLE EMPLEADO MODIFY (CORREO CONSTRAINT UQ_EMPLEADO_CORREO UNIQUE);

ALTER TABLE PRODUCTO ADD CONSTRAINT CHK_PRODUCTO_STOCK_MIN CHECK (STOCK >= 10);

ALTER TABLE VENTA ADD CONSTRAINT CHK_VENTA_MONTO CHECK (MONTO_TOTAL >= 0);

INSERT INTO AFP (NOMBRE) VALUES ('Provida');
INSERT INTO AFP (NOMBRE) VALUES ('Cuprum');
INSERT INTO AFP (NOMBRE) VALUES ('Habitat');

INSERT INTO SALUD (NOMBRE) VALUES ('Fonasa');
INSERT INTO SALUD (NOMBRE) VALUES ('Isapre Colmena');
INSERT INTO SALUD (NOMBRE) VALUES ('Isapre Consalud');

INSERT INTO EMPLEADO (RUN, DV, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, ACTIVO, SUELDO, BONO_JEFATURA, CORREO, ID_AFP, ID_SALUD)
VALUES ('12345678','K','Marta','González','López','S',650000,50000,'marta.gonzalez@dona-marta.cl',1,1);
INSERT INTO EMPLEADO (RUN, DV, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, ACTIVO, SUELDO, BONO_JEFATURA, CORREO, ID_AFP, ID_SALUD)
VALUES ('20456789','3','Pedro','Ramírez','Soto','S',780000,NULL,'pedro.ramirez@dona-marta.cl',2,2);
INSERT INTO EMPLEADO (RUN, DV, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, ACTIVO, SUELDO, BONO_JEFATURA, CORREO, ID_AFP, ID_SALUD)
VALUES ('18765432','9','Sofía','Pérez','Mora','N',520000,NULL,'sofia.perez@dona-marta.cl',3,1);
INSERT INTO EMPLEADO (RUN, DV, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, ACTIVO, SUELDO, BONO_JEFATURA, CORREO, ID_AFP, ID_SALUD)
VALUES ('15678901','2','Andrés','Silva','Rojas','S',590000,30000,'andres.silva@dona-marta.cl',1,3);

INSERT INTO VENDEDOR (ID_EMPLEADO) SELECT ID_EMPLEADO FROM EMPLEADO WHERE ACTIVO='S';

INSERT INTO MEDIO_PAGO (NOMBRE) VALUES ('EFECTIVO');
INSERT INTO MEDIO_PAGO (NOMBRE) VALUES ('TARJETA');
INSERT INTO MEDIO_PAGO (NOMBRE) VALUES ('TRANSFERENCIA');

INSERT INTO PRODUCTO (NOMBRE, PRECIO, STOCK) VALUES ('Pan Hallulla', 1500, 50);
INSERT INTO PRODUCTO (NOMBRE, PRECIO, STOCK) VALUES ('Leche Entera 1L', 1200, 80);
INSERT INTO PRODUCTO (NOMBRE, PRECIO, STOCK) VALUES ('Azúcar 1kg', 1100, 60);

INSERT INTO VENTA (ID_VENTA, FECHA_VENTA, MONTO_TOTAL, ID_VENDEDOR, ID_MEDIO_PAGO)
VALUES (SEQ_VENTA.NEXTVAL, SYSDATE, 2700, (SELECT MIN(ID_VENDEDOR) FROM VENDEDOR), 1);
INSERT INTO DETALLE_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES ((SELECT MAX(ID_VENTA) FROM VENTA), 1, 1, 1500, 1500);
INSERT INTO DETALLE_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES ((SELECT MAX(ID_VENTA) FROM VENTA), 2, 1, 1200, 1200);

INSERT INTO VENTA (ID_VENTA, FECHA_VENTA, MONTO_TOTAL, ID_VENDEDOR, ID_MEDIO_PAGO)
VALUES (SEQ_VENTA.NEXTVAL, SYSDATE, 2300, (SELECT MIN(ID_VENDEDOR) FROM VENDEDOR WHERE ID_VENDEDOR <> (SELECT MIN(ID_VENDEDOR) FROM VENDEDOR)), 2);
INSERT INTO DETALLE_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
VALUES ((SELECT MAX(ID_VENTA) FROM VENTA), 3, 2, 1100, 2200);
UPDATE VENTA SET MONTO_TOTAL = (SELECT SUM(SUBTOTAL) FROM DETALLE_VENTA WHERE DETALLE_VENTA.ID_VENTA = VENTA.ID_VENTA);

SELECT ID_EMPLEADO AS IDENTIFICADOR,
       NOMBRES||' '||APELLIDO_PATERNO||NVL(' '||APELLIDO_MATERNO,'') AS NOMBRE_COMPLETO,
       SUELDO AS SALARIO,
       NVL(BONO_JEFATURA,0) AS BONIFICACION,
       (SUELDO + NVL(BONO_JEFATURA,0)) AS SALARIO_SIMULADO
FROM EMPLEADO
WHERE ACTIVO = 'S' AND BONO_JEFATURA IS NOT NULL
ORDER BY SALARIO_SIMULADO DESC, APELLIDO_PATERNO DESC;

SELECT ID_EMPLEADO AS EMPLEADO,
       SUELDO AS SUELDO,
       ROUND(SUELDO*0.08,2) AS POSIBLE_AUMENTO,
       ROUND(SUELDO*1.08,2) AS SALARIO_SIMULADO
FROM EMPLEADO
WHERE SUELDO BETWEEN 550000 AND 800000
ORDER BY SUELDO ASC;
