
-- ======================================================================
-- Vivir Mejor - Residencias de Estadía Prolongada (Semana 3 - MER-E)
-- Modelo Relacional (DDL) para importar en Oracle SQL Data Modeler
-- Uso: File > Import > DDL File  → luego Engineer to Logical Model
--      para obtener el MER (Barker) y Bachman (tipos de datos).
-- ======================================================================

----------------------------------------------------------------------
-- Limpieza defensiva (ignorar errores si las tablas no existen)
----------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE OCUPACION CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE ANEXO CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE RESIDENTE_PERMANENTE CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE RESIDENTE_TEMPORAL CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE RESIDENTE CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE CONTRATO CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE APODERADO CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE MEDICO CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE CUIDADOR CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE PERSONAL CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE HABITACION CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE RESIDENCIA CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
----------------------------------------------------------------------
-- ENTIDADES ORGANIZACIONALES
----------------------------------------------------------------------
CREATE TABLE RESIDENCIA (
  ID_RESIDENCIA   VARCHAR2(12)  NOT NULL,
  NOMBRE          VARCHAR2(100) NOT NULL,
  COMUNA          VARCHAR2(80)  NOT NULL,
  CONSTRAINT PK_RESIDENCIA PRIMARY KEY (ID_RESIDENCIA)
);

CREATE TABLE HABITACION (
  ID_HABITACION   VARCHAR2(12)  NOT NULL,
  ID_RESIDENCIA   VARCHAR2(12)  NOT NULL,
  NUMERO          VARCHAR2(10)  NOT NULL,
  TIPO            VARCHAR2(15)  NOT NULL, -- INDIVIDUAL / COMPARTIDA
  CONSTRAINT PK_HABITACION PRIMARY KEY (ID_HABITACION),
  CONSTRAINT FK_HAB_RESIDENCIA FOREIGN KEY (ID_RESIDENCIA) REFERENCES RESIDENCIA (ID_RESIDENCIA),
  CONSTRAINT CHK_HAB_TIPO CHECK (UPPER(TIPO) IN ('INDIVIDUAL','COMPARTIDA'))
);

----------------------------------------------------------------------
-- PERSONAS Y ROLES (MER-E: supertipo/subtipos exclusivos)
----------------------------------------------------------------------
CREATE TABLE PERSONAL (
  ID_PERSONAL     VARCHAR2(12)  NOT NULL,
  RUT             VARCHAR2(15)  NOT NULL,
  NOMBRE          VARCHAR2(100) NOT NULL,
  FECHA_INGRESO   DATE          NOT NULL,
  ID_RESIDENCIA   VARCHAR2(12)  NOT NULL, -- cada personal trabaja en una sola residencia
  ROL             VARCHAR2(12)  NOT NULL, -- MEDICO / CUIDADOR (exclusivo)
  CONSTRAINT PK_PERSONAL PRIMARY KEY (ID_PERSONAL),
  CONSTRAINT UQ_PERSONAL_RUT UNIQUE (RUT),
  CONSTRAINT FK_PER_RESIDENCIA FOREIGN KEY (ID_RESIDENCIA) REFERENCES RESIDENCIA (ID_RESIDENCIA),
  CONSTRAINT CHK_PER_ROL CHECK (UPPER(ROL) IN ('MEDICO','CUIDADOR'))
);

CREATE TABLE MEDICO (
  ID_PERSONAL     VARCHAR2(12)  NOT NULL, -- PK = FK a PERSONAL
  ESPECIALIDAD    VARCHAR2(80)  NOT NULL,
  ID_SUPERVISOR   VARCHAR2(12),          -- opcional, recursiva a MEDICO
  CONSTRAINT PK_MEDICO PRIMARY KEY (ID_PERSONAL),
  CONSTRAINT FK_MEDICO_PERSONAL FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL (ID_PERSONAL),
  CONSTRAINT FK_MEDICO_SUPERVISOR FOREIGN KEY (ID_SUPERVISOR) REFERENCES MEDICO (ID_PERSONAL)
);

CREATE TABLE CUIDADOR (
  ID_PERSONAL     VARCHAR2(12)  NOT NULL, -- PK = FK a PERSONAL
  CONSTRAINT PK_CUIDADOR PRIMARY KEY (ID_PERSONAL),
  CONSTRAINT FK_CUIDADOR_PERSONAL FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL (ID_PERSONAL)
);

----------------------------------------------------------------------
-- APODERADOS, CONTRATOS Y ANEXOS
----------------------------------------------------------------------
CREATE TABLE APODERADO (
  ID_APODERADO    VARCHAR2(12)  NOT NULL,
  NOMBRE          VARCHAR2(100) NOT NULL,
  CONTACTO        VARCHAR2(100) NOT NULL, -- teléfono/email
  CONSTRAINT PK_APODERADO PRIMARY KEY (ID_APODERADO)
);

CREATE TABLE CONTRATO (
  ID_CONTRATO       VARCHAR2(12)  NOT NULL,
  ID_APODERADO      VARCHAR2(12)  NOT NULL,
  FECHA_INICIO      DATE          NOT NULL,
  FECHA_TERMINO     DATE,                     -- puede ser nula (activo)
  TIPO_FINANCIAMIENTO VARCHAR2(30) NOT NULL,  -- PRIVADO, SEGURO, SUBSIDIO, etc.
  CONSTRAINT PK_CONTRATO PRIMARY KEY (ID_CONTRATO),
  CONSTRAINT FK_CON_APODERADO FOREIGN KEY (ID_APODERADO) REFERENCES APODERADO (ID_APODERADO)
);

CREATE TABLE RESIDENTE (
  ID_RESIDENTE     VARCHAR2(12)  NOT NULL,
  NOMBRE           VARCHAR2(100) NOT NULL,
  EDAD             NUMBER(3,0)   NOT NULL,
  AUTONOMIA        CHAR(1)       NOT NULL,   -- S / N
  CONSTRAINT PK_RESIDENTE PRIMARY KEY (ID_RESIDENTE),
  CONSTRAINT CHK_RES_AUTONOMIA CHECK (UPPER(AUTONOMIA) IN ('S','N'))
);

CREATE TABLE RESIDENTE_PERMANENTE (
  ID_RESIDENTE       VARCHAR2(12)  NOT NULL,  -- PK = FK a RESIDENTE
  HISTORIAL_CLINICO  VARCHAR2(500) NOT NULL,
  CONSTRAINT PK_RES_PERM PRIMARY KEY (ID_RESIDENTE),
  CONSTRAINT FK_RES_PERM_RES FOREIGN KEY (ID_RESIDENTE) REFERENCES RESIDENTE (ID_RESIDENTE)
);

CREATE TABLE RESIDENTE_TEMPORAL (
  ID_RESIDENTE            VARCHAR2(12) NOT NULL,  -- PK = FK a RESIDENTE
  DIAS_ESTADIA_PREVISTOS  NUMBER(4,0)  NOT NULL,
  CONSTRAINT PK_RES_TEMP PRIMARY KEY (ID_RESIDENTE),
  CONSTRAINT FK_RES_TEMP_RES FOREIGN KEY (ID_RESIDENTE) REFERENCES RESIDENTE (ID_RESIDENTE)
);

CREATE TABLE ANEXO (
  ID_ANEXO         VARCHAR2(14)  NOT NULL,
  ID_CONTRATO      VARCHAR2(12)  NOT NULL,
  ID_RESIDENTE     VARCHAR2(12)  NOT NULL,
  FECHA_INICIO     DATE          NOT NULL,
  FECHA_TERMINO    DATE,                   -- nula = vigente
  OBSERVACIONES    VARCHAR2(300),
  CONSTRAINT PK_ANEXO PRIMARY KEY (ID_ANEXO),
  CONSTRAINT FK_ANEXO_CONTRATO  FOREIGN KEY (ID_CONTRATO)  REFERENCES CONTRATO (ID_CONTRATO),
  CONSTRAINT FK_ANEXO_RESIDENTE FOREIGN KEY (ID_RESIDENTE) REFERENCES RESIDENTE (ID_RESIDENTE),
  CONSTRAINT CHK_ANEXO_FECHAS CHECK (FECHA_TERMINO IS NULL OR FECHA_TERMINO >= FECHA_INICIO)
);

----------------------------------------------------------------------
-- OCUPACION: historial de habitación por residente (exclusividad actual)
----------------------------------------------------------------------
CREATE TABLE OCUPACION (
  ID_OCUPACION    VARCHAR2(14)  NOT NULL,
  ID_RESIDENTE    VARCHAR2(12)  NOT NULL,
  ID_HABITACION   VARCHAR2(12)  NOT NULL,
  FECHA_INICIO    DATE          NOT NULL,
  FECHA_TERMINO   DATE,                    -- nula = ocupación activa
  CONSTRAINT PK_OCUPACION PRIMARY KEY (ID_OCUPACION),
  CONSTRAINT FK_OCUP_RESIDENTE  FOREIGN KEY (ID_RESIDENTE)  REFERENCES RESIDENTE (ID_RESIDENTE),
  CONSTRAINT FK_OCUP_HABITACION FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION (ID_HABITACION),
  CONSTRAINT CHK_OCUP_FECHAS CHECK (FECHA_TERMINO IS NULL OR FECHA_TERMINO >= FECHA_INICIO)
);

----------------------------------------------------------------------
-- ÍNDICES sugeridos
----------------------------------------------------------------------
CREATE INDEX IX_HAB_RESIDENCIA   ON HABITACION (ID_RESIDENCIA);
CREATE INDEX IX_PER_RESIDENCIA   ON PERSONAL (ID_RESIDENCIA);
CREATE INDEX IX_MED_SUPERVISOR   ON MEDICO (ID_SUPERVISOR);
CREATE INDEX IX_ANEXO_CONTRATO   ON ANEXO (ID_CONTRATO);
CREATE INDEX IX_ANEXO_RESIDENTE  ON ANEXO (ID_RESIDENTE);
CREATE INDEX IX_OCUP_RESIDENTE   ON OCUPACION (ID_RESIDENTE);
CREATE INDEX IX_OCUP_HABITACION  ON OCUPACION (ID_HABITACION);
